
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-image
  namespace: apps
spec:
  params:
    - name: APP_NAME
      description: The app name, also the directory where the app is located
      type: string
     - name: INCLUDING_SOURCE
      description: Whether the build should include binary source
      type: boolean     
    - name: SOURCE_DIR
      description: The directory to the source to be included with s2i image, relative to APP_NAME directory, required if  params.INCLUDING_SOURCE=true
      type: string
      default: ""
  steps:
    - name: create-build-config
      image: quay.io/pnminh232/ubi9-build-tools-minimal:1.0.0
      workingDir: $(workspaces.source.path)/${params.APP_NAME}/helm/build-app
      script: |
        #!/bin/sh
        set -e
        helm dependency update
        helm upgrade --install ${params.APP_NAME} .
    - name: run-s2i-build
      image: quay.io/pnminh232/ubi9-build-tools-minimal:1.0.0
      workingDir: $(workspaces.source.path)/${params.APP_NAME}
      script: |
        #!/bin/sh
        set -e
        if [ "$INCLUDING_SOURCE" = "true" ]; then
          oc start-build ${params.APP_NAME} --from-dir="$(params.SOURCE_DIR)" --follow
        else
          oc start-build ${params.APP_NAME} --follow
        fi
  workspaces:
    - name: source
      description: "Workspace containing the build"