apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-build
  namespace: apps
spec:
  params:
    - name: PATH_CONTEXT
      description: The directory where the npm commands will be run
      type: string
  steps:
    - name: npm-install
      image: quay.io/pnminh232/ubi9-build-image:1.0.0
      workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
      script: |
        #!/bin/sh
        set -e
        export CYPRESS_CACHE_FOLDER=/tmp/.cache
        npm install
    - name: npm-test
      image: quay.io/pnminh232/ubi9-build-image:1.0.0
      workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
      script: |
        #!/bin/sh
        set -e
        npm test
    - name: npm-ci
      image: quay.io/pnminh232/ubi9-build-image:1.0.0
      workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
      script: |
        #!/bin/sh
        set -e
        npm ci
  workspaces:
    - name: source
      description: "Workspace containing the build"