
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-app
  namespace: apps
spec:
  params:
    - default: todo-ui
      description: Application name
      name: app
      type: string
    - description: Repo url
      name: repo-url
      type: string
    - default: master
      description: Repo revision
      name: repo-revision
      type: string
  tasks:
    - name: git-clone-source
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.repo-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: retrieve-app-configs
      params:
        - name: app-config-file-path
          value: apps/$(params.app)/app-config.yaml
      runAfter:
        - git-clone-source
      taskRef:
        kind: Task
        name: app-configs
      workspaces:
        - name: source
          workspace: source
    - name: npm-build
      params:
        - name: PATH_CONTEXT  
          value: apps/$(params.app)
      runAfter:
        - retrieve-app-configs
      taskRef:
        kind: Task
        name: npm-build
      when:
        - input: $(tasks.retrieve-app-configs.results.app-configs.build-type)
          operator: in
          values:
            - npm
      workspaces:
        - name: source
          workspace: source
    - name: maven-build
      params:
        - name: PATH_CONTEXT  
          value: apps/$(params.app)
      runAfter:
        - retrieve-app-configs
      taskRef:
        kind: Task
        name: maven-build
      when:
        - input: $(tasks.retrieve-app-configs.results.app-configs.build-type)
          operator: in
          values:
            - mvn
      workspaces:
        - name: source
          workspace: source
    - name: build-and-push-image
      params:
        - name: APP_NAME  
          value: $(params.app)
        - name: SOURCE_DIR
          value: $(tasks.retrieve-app-configs.results.app-configs.build-binary-dir)
      taskRef: 
        kind: Task
        name: build-and-push-image
      runAfter:
        - npm-build
        - maven-build
      workspaces:
        - name: source
          workspace: source
  workspaces:
    - name: source