
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-app
  namespace: apps
spec:
  params:
    - name: app
      default: todo-ui
      description: 'Application name'
      type: string
    - name: repo-url
      description: 'Repo url'
      type: string
    - name: repo-revision
      description: 'Repo revision'
      default: master
      type: string
  tasks:
    - name: git-clone-source
      params:
        - name: url
          value: >-
            $(params.repo-url)
        - name: revision
          value: $(params.repo-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
  workspaces:
    - name: source